services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 9000:9000
    environment:
      UPLOAD_LIMIT: 2G
      PMA_HOST: mariadb
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit
    volumes:
      - /var/bleeter/rabbit
        
  account-service:
    image: accounts-service:latest
    container_name: accounts-service
    depends_on:
      - account-service-db
      - rabbitmq
    networks:
      - rabbit
    ports:
      - 5001:5001
        
  account-service-db:
    image: mariadb
    container_name: accounts-service-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: accounts
    volumes:
      - db:/var/bleeter/data/accounts
  
  bleet-service:
    image: bleets-service:latest
    container_name: bleets-service
    depends_on:
      - bleets-service-db
      - rabbitmq
    networks:
      - rabbit
    ports:
      - 5002:5002
      
  bleets-service-db:
    image: mariadb
    container_name: bleets-service-db
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: bleets
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    volumes:
      - db:/var/bleeter/data/bleets

  private-messages-service:
    image: private-messages-service:latest
    container_name: private-messages-serivce
    depends_on:
      - private-messages-service-db
    ports:
      - 5003:5003
  
  private-messages-service-db:
    image: mariadb
    container_name: private-messages-db
    ports:
      - 3308:3308
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: pms
    volumes:
      - db:/var/bleeter/data/pms
        
  notifications-service:
    image: notifications-service:latest
    container_name: notifications-service
    depends_on:
      - notifications-service-db
      - rabbitmq
    networks:
        - rabbit
    ports:
      - 5004:5004
  
  notifications-service-db:
    image: mariadb
    container_name: notifications-service-db
    ports:
      - 3309:3309
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: notifications
    volumes:
      - db:/var/bleeter/data/notifications-service
  
volumes:
  db:
    name: "bleeter"
    driver: local
    
networks:
  rabbit:
    name: "rabbit"
    driver: bridge
    
    
