services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: accounts

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9000:80
    environment:
      UPLOAD_LIMIT: 2G
      PMA_HOST: mariadb