services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 9000:9000
    environment:
      UPLOAD_LIMIT: 2G
      PMA_HOST: mariadb
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit
    volumes:
      - /var/bleeter/rabbit
        
  account-service:
    image: accounts-service:latest
    container_name: accounts-service
    depends_on:
      - account-service-db
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5401
    networks:
      - rabbit
      - accounts-db
    ports:
      - 5001:5001
      - 5401:5401
        
  account-service-db:
    image: mariadb
    container_name: accounts-service-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: accounts
    networks:
      - accounts-db
    volumes:
      - db:/var/bleeter/data/accounts
  
  bleet-service:
    image: bleets-service:latest
    container_name: bleets-service
    depends_on:
      - bleets-service-db
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5402
    networks:
      - rabbit
      - bleets-db
    ports:
      - 5002:5002
      - 5402:5402
      
  bleets-service-db:
    image: mariadb
    container_name: bleets-service-db
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: bleets
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    networks:
      - bleets-db
    volumes:
      - db:/var/bleeter/data/bleets
        
  notifications-service:
    image: notifications-service:latest
    container_name: notifications-service
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5404
    networks:
        - rabbit
    ports:
      - 5004:5004
      - 5404:5404
        
  bleeter-react:
    image: bleeter-react
    container_name: bleeter-react
    ports:
      - 80:80
      - 8080:8080
      - 443:443
  
volumes:
  db:
    name: "bleeter"
    driver: local
    
networks:
  rabbit:
    name: "rabbit"
    driver: bridge
  accounts-db:
    name: "accounts-db"
    driver: bridge
  bleets-db:
    name: "bleets-db"
    driver: bridge
    
    
